### ISSUE TITLE
Invalid redefinition of type FixeEffectSolverGPU

### ISSUE THREAD

**Issue by dwinkler1** [FixedEffects/FixedEffects.jl#42]
When loading `FixedEffectModels` after merging #41 I get the following error:

```

┌ Error: evaluation error starting at /home/daniel/.julia/packages/FixedEffects/AAdnN/src/FixedEffectSolvers/FixedEffectSolverGPU.jl:108
│   mod = FixedEffects
│   ex =
│    quote
│        #= /home/daniel/.julia/packages/FixedEffects/AAdnN/src/FixedEffectSolvers/FixedEffectSolverGPU.jl:108 =#
│        mutable struct FixedEffectSolverGPU{T} <: AbstractFixedEffectSolver{T}
│            #= /home/daniel/.julia/packages/FixedEffects/AAdnN/src/FixedEffectSolvers/FixedEffectSolverGPU.jl:109 =#
│            m::FixedEffectLinearMapGPU{T}
│            #= /home/daniel/.julia/packages/FixedEffects/AAdnN/src/FixedEffectSolvers/FixedEffectSolverGPU.jl:110 =#
│            weights::CuVector{T}
│            #= /home/daniel/.julia/packages/FixedEffects/AAdnN/src/FixedEffectSolvers/FixedEffectSolverGPU.jl:111 =#
│            b::CuVector{T}
│            #= /home/daniel/.julia/packages/FixedEffects/AAdnN/src/FixedEffectSolvers/FixedEffectSolverGPU.jl:112 =#
│            r::CuVector{T}
│            #= /home/daniel/.julia/packages/FixedEffects/AAdnN/src/FixedEffectSolvers/FixedEffectSolverGPU.jl:113 =#
│            x::FixedEffectCoefficients{<:AbstractVector{T}}
│            #= /home/daniel/.julia/packages/FixedEffects/AAdnN/src/FixedEffectSolvers/FixedEffectSolverGPU.jl:114 =#
│            v::FixedEffectCoefficients{<:AbstractVector{T}}
│            #= /home/daniel/.julia/packages/FixedEffects/AAdnN/src/FixedEffectSolvers/FixedEffectSolverGPU.jl:115 =#
│            h::FixedEffectCoefficients{<:AbstractVector{T}}
│            #= /home/daniel/.julia/packages/FixedEffects/AAdnN/src/FixedEffectSolvers/FixedEffectSolverGPU.jl:116 =#
│            hbar::FixedEffectCoefficients{<:AbstractVector{T}}
│            #= /home/daniel/.julia/packages/FixedEffects/AAdnN/src/FixedEffectSolvers/FixedEffectSolverGPU.jl:117 =#
│            tmp::Vector{T}
│            #= /home/daniel/.julia/packages/FixedEffects/AAdnN/src/FixedEffectSolvers/FixedEffectSolverGPU.jl:118 =#
│            fes::Vector{<:FixedEffect}
│        end
│    end
│   exception =
│    invalid redefinition of type FixedEffectSolverGPU
│    Stacktrace:
│     [1] get_call_framecode(::Array{Any,1}, ::JuliaInterpreter.FrameCode, ::Int64; enter_generated::Bool) at /home/daniel/.julia/packages/JuliaInterpreter/CPmYX/src/localmethtable.jl:64
└ @ Revise ~/.julia/packages/Revise/BqeJF/src/lowered.jl:106
```

Is this related to Revise? I could not find another definition

**Comment by matthieugomez** [comment]
Thanks for your help. The issue appears only when using Revise?

**Comment by matthieugomez** [comment]
Closing, but let me know if the problem is not solved.

**Comment by dwinkler1** [comment]
Sorry I have not been able to reproduce this since but cannot spare the GPU at the moment to investigate this further. I will reopen if I can reproduce this on a spare gpu.
